version: "3.8"

services:
  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile.sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=user
      - SONAR_JDBC_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: bso-jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
  sonarqube_data:
